apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mydb1
spec:
  replicas: 3
  selector:
    matchLabels:
      team: prod
  template:
    metadata:
      labels:
        team: prod
        tier: front
    spec:
      containers:
        - name: "c1"
          image: "mysql"
