apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mydb1
spec:
  replicas: 1
  selector:
    matchLabels:
      team: prod
  template:
    metadata:
      labels:
        team: prod
    spec:
      containers:
        - name: "c1"
          image: "mysql"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: redhat
            - name: MYSQL_DATABASE
              value: mydata
            - name: MYSQL_USER
              value: himanshu
            - name: MYSQL_PASSWORD
              value: redhat
