apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1

spec:
apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
    - name: "c1"
      image: "vimal13/apache-webserver-php"
